// starters/vue-starter-ts/components/article/ArticleView.vue
<script setup lang="ts">
import type { Article } from "@pantheon-systems/pcc-vue-sdk";
import {
  ArticleRenderer,
  getArticleTitle,
} from "@pantheon-systems/pcc-vue-sdk/components";
import type { PropType } from "vue";
import "@pantheon-systems/pcc-vue-sdk/components/style.css";
import { smartComponentMap } from "../smart-components";

defineProps({
  article: {
    type: Object as PropType<Article | null>,
  },
  error: {
    type: Boolean,
    required: false,
    default: false,
  },
});
</script>

<template>
  <div class="prose mx-4 mt-16 text-black sm:mx-6 lg:mx-auto">
    <h2 v-if="error" class="text-red-500">
      Failed to load article, please try again.
    </h2>
    <h2 v-else-if="!article">Loading...</h2>
    <div v-else>
      <div>
        <div class="text-5xl font-bold">
          {{ getArticleTitle(article) }}
        </div>
        <p class="py-2" v-if="article.updatedAt">
          {{
            new Date(article.updatedAt).toLocaleDateString("en-US", {
              year: "numeric",
              month: "long",
              day: "numeric",
            })
          }}
        </p>
      </div>
      <ArticleRenderer
        :article="article"
        :smart-component-map="smartComponentMap"
      >
      </ArticleRenderer>
    </div>
  </div>
</template>

// starters/nextjs-starter-approuter-ts/components/article-view.tsx
"use client"
import { useArticle } from "@pantheon-systems/pcc-react-sdk";
import type { Article } from "@pantheon-systems/pcc-react-sdk";
import { ArticleRenderer } from "@pantheon-systems/pcc-react-sdk/components";
import { clientSmartComponentMap } from "./smart-components/client-components";

export default function ArticleView({
  article,
  onlyContent,
}: {
  article: Article;
  onlyContent?: boolean;
}) {
  const { data } = useArticle(
    article.id,
    {
      publishingLevel: article.publishingLevel,
      contentType: "TREE_PANTHEON_V2",
    },
    {
      skip: article.publishingLevel !== "REALTIME",
    },
  );

  const hydratedArticle = data?.article ?? article;

  return (
    <ArticleRenderer
      article={hydratedArticle}
      renderTitle={(titleElement) => (
        <div>
          <div className="text-3xl font-bold md:text-4xl">{titleElement}</div>

          {article.updatedAt ? (
            <p className="py-2">
              Last Updated:{" "}
              {new Date(article.updatedAt).toLocaleDateString("en-US", {
                year: "numeric",
                month: "long",
                day: "numeric",
              })}
            </p>
          ) : null}

          <hr className="mt-6 mb-8" />
        </div>
      )}
      smartComponentMap={clientSmartComponentMap}
      __experimentalFlags={{ disableAllStyles: !!onlyContent }}
    />
  );
}
