// nextjs-starter/pages/index.jsx
import { NextSeo } from "next-seo";
import Image from "next/image";
import Layout from "../components/layout";
import { PostGrid } from "../components/grid";
import { getArticles } from "@pantheon-systems/pcc-react-sdk";
import { pantheonClient } from "../lib/PantheonClient";

export default function Home({ articles }) {
  const HomepageHeader = () => (
    <div className="prose sm:prose-xl mt-20 flex flex-col mx-auto max-w-fit">
      <h1 className="prose text-4xl text-center h-full">
        Welcome to{" "}
        <a
          className="text-blue-600 no-underline hover:underline"
          href="https://nextjs.org"
        >
          Next.js!
        </a>
      </h1>
      <div className="text-2xl">
        <div className="bg-black text-white rounded flex items-center justify-center p-4">
          Decoupled PCC on{" "}
          <Image
            src="/pantheon.png"
            alt="Pantheon Logo"
            style={{
              margin: 0,
            }}
            width={191}
            height={60}
          />
        </div>
      </div>
    </div>
  );

  return (
    <Layout>
      <NextSeo
        title="Decoupled Next PCC Demo"
        description="Generated by create-pantheon-decoupled-kit."
      />
      <HomepageHeader />
      <section>
        <PostGrid contentType="posts" data={articles} />
      </section>
    </Layout>
  );
}

export async function getServerSideProps() {
  const articles = await getArticles(pantheonClient);

  return {
    props: {
      articles,
    },
  };
}

// starters/vue-starter-ts/pages/index.vue
<script setup lang="ts">
import ArticleLink from "../components/ArticleLink.vue";

import { ArticleWithoutContent } from "@pantheon-systems/pcc-vue-sdk";

const { data, error } = await useFetch<ArticleWithoutContent[]>("/api/articles/")
</script>

<template>
  <div class="flex flex-col mx-auto mt-20 prose sm:prose-xl max-w-fit">
    <h1 class="h-full text-4xl prose text-center">
      Welcome to
      <nuxt-link class="text-blue-600 no-underline hover:underline" href="https://nuxt.com">
        Nuxt!
      </nuxt-link>
    </h1>
    <div class="text-2xl">
      <div class="flex items-center justify-center max-w-lg p-4 mx-auto text-white bg-black rounded">
        Decoupled PCC on
        <img src="/pantheon.png" style="margin: 0;" alt="Pantheon Logo" :width="191" :height="60" />
      </div>
    </div>

    <section>
      <h2 v-if="error" class="text-red-500">
        Failed to load articles, please try again.
      </h2>
      <h2 v-else-if="!data">
        Loading...
      </h2>
      <div v-else class="grid gap-5 mx-auto mt-12 max-w-content lg:max-w-screen-lg lg:grid-cols-3">
        <article-link v-for="article in data" :key="article.id" :id="article.id" :title="article.title || 'Untitled'"
          :tags="article.tags || []" />
      </div>
    </section>
  </div>
</template>
